inveniosoftware/invenio-records-ui

- .travis.yml
- INSTALL.rst
- docs/api.rst
- docs/usage.rst
- examples/app.py
- invenio_records_ui/__init__.py
- invenio_records_ui/ext.py
- invenio_records_ui/signals.py
- invenio_records_ui/templates/invenio_records_ui/tombstone.html
- invenio_records_ui/views.py
- setup.py
- tests/test_invenio_records_ui.py
* Adds support for record tombstones.
* Adds support for redirecting/merging persistent identifiers.
> views: tombstones and redirects

- CHANGES.rst
- RELEASE-NOTES.rst
- examples/app.py
- examples/permsapp.py
- invenio_records_ui/__init__.py
- invenio_records_ui/ext.py
- invenio_records_ui/version.py
- invenio_records_ui/views.py
- requirements-devel.txt
- setup.py
- tests/conftest.py
- tests/test_invenio_records_ui.py
> release: v1.0.0a3

- AUTHORS.rst
- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_records_ui/version.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> release: v1.0.0a4

- invenio_records_ui/version.py
> version: post-release bump

- .editorconfig
- .travis.yml
- examples/app.py
- examples/permsapp.py
- invenio_records_ui/__init__.py
- requirements-devel.txt
- run-tests.sh
- tests/conftest.py
* Changes deployment condition to "released" requirements.
(closes #18)
> travis: deployment on release requirements pass

- .travis.yml
- invenio_records_ui/__init__.py
- invenio_records_ui/views.py
- tests/test_invenio_records_ui.py
* Adds support for using custom view functions. (closes #5)
> views: custom view function support

- AUTHORS.rst
- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_records_ui/version.py
> release: v1.0.0a5

- invenio_records_ui/views.py
- tests/test_invenio_records_ui.py
* Fixes issue with keyword arguments not being passed down to custom
view functions.
> views: custom view function fix

- invenio_records_ui/views.py
> views: configurable record class

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_records_ui/version.py
> release: v1.0.0a6

- docs/conf.py
- invenio_records_ui/views.py
- tests/test_invenio_records_ui.py
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> views: methods configuration addition and sphinx fix

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_records_ui/version.py
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> release: v1.0.0a7

- tests/helpers.py
- tests/test_invenio_records_ui.py
* Sets a custom permission check on tests.
(addresses inveniosoftware/invenio-records#138)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> tests: custom permission check

- .travis.yml
- .tx/config
- AUTHORS.rst
- MANIFEST.in
- docs/api.rst
- docs/conf.py
- docs/index.rst
- invenio_records_ui/ext.py
- setup.cfg
- setup.py
- tests/conftest.py
- tests/helpers.py
> global: code style, copyrights, and authors

- examples/app-fixtures.sh
- examples/app-recreate.sh
- examples/app-setup.sh
- examples/app-teardown.sh
- examples/app.py
- examples/permsapp-recreate.sh
- examples/permsapp.py
- tests/test_examples_app.py
* Adds test_examples_app.py. (closes #56)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> tests: addition of test_examples_app.py

- invenio_records_ui/views.py
- setup.py
- tests/conftest.py
- tests/test_invenio_records_ui.py
- tests/test_record_files.py
depends on https://github.com/inveniosoftware/invenio-files-rest/pull/135, https://github.com/inveniosoftware/invenio-records-files/pull/38, https://github.com/inveniosoftware/invenio-records-files/pull/39 and more ...
> tests: integration with record files

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_records_ui/version.py
> release: v1.0.0a9

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_records_ui/version.py
- invenio_records_ui/views.py
- setup.py
Build [here](https://travis-ci.org/diegodelemos/invenio-records-ui/builds/263131361) 💚
> release: v1.0.0b1

- .editorconfig
- .gitignore
- .travis.yml
- .tx/config
- AUTHORS.rst
- CHANGES.rst
- CONTRIBUTING.rst
- INSTALL.rst
- MANIFEST.in
- README.rst
- RELEASE-NOTES.rst
- docs/conf.py
- docs/configuration.rst
- docs/examplesapp.rst
- examples/app.py
- examples/permsapp.py
- pytest.ini
- run-tests.sh
- setup.cfg
- setup.py
- tests/conftest.py
> global: release checklist

- .gitignore
- AUTHORS.rst
- CONTRIBUTING.rst
- docs/Makefile
- docs/make.bat
- docs/usage.rst
- invenio_records_ui/translations/es/LC_MESSAGES/messages.po
- invenio_records_ui/translations/messages.pot
- run-tests.sh
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>
> global: release checklist leftovers

- .travis.yml
- CHANGES.rst
- invenio_records_ui/version.py
- requirements-devel.txt
- setup.py
* drop support for Python 2.7
* update travis.yml
* closes #84
> global: centrally manage Flask dependency

- invenio_records_ui/templates/semantic-ui/invenio_records_ui/base.html
- invenio_records_ui/templates/semantic-ui/invenio_records_ui/detail.html
- invenio_records_ui/templates/semantic-ui/invenio_records_ui/export.html
- invenio_records_ui/templates/semantic-ui/invenio_records_ui/export_well.html
- invenio_records_ui/templates/semantic-ui/invenio_records_ui/tombstone.html
> ui: add initial semantic-ui integration

- CHANGES.rst
- invenio_records_ui/version.py
Closes https://github.com/inveniosoftware/invenio-records-ui/issues/92
Kudos to the release doc! Useful <https://invenio.readthedocs.io/en/master/community/contributing/maintainers-guide/releasing.html#module-release>
> release: v1.2.0

- AUTHORS.rst
- babel.ini
Fix err AttributeError: module 'jinja2.ext' has no attribute 'autoescape' when extract messages for translation
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
1. You license your contribution under the same terms as the current …
> config: fix extract messages err

- CHANGES.rst
- invenio_records_ui/__init__.py
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
2. You agree that you have the right to license …
> release: v1.2.1

- invenio_records_ui/__init__.py
- invenio_records_ui/templates/invenio_records_ui/export.html
- invenio_records_ui/templates/invenio_records_ui/tombstone.html
- invenio_records_ui/templates/semantic-ui/invenio_records_ui/export.html
- invenio_records_ui/templates/semantic-ui/invenio_records_ui/tombstone.html
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
2. You agree that you have the right to license …
> i18n: translate export & tombstone templates

- CHANGES.rst
- invenio_records_ui/__init__.py
- invenio_records_ui/templates/invenio_records_ui/export.html
- invenio_records_ui/templates/invenio_records_ui/tombstone.html
- invenio_records_ui/version.py
> I18n: Mark Missing Translations Backport

- .github/workflows/i18n-pull.yml
- .github/workflows/i18n-push.yml
> feat: add i18n workflows for pulling and pushing translations

- .github/workflows/i18n-pull.yml
- .github/workflows/i18n-push.yml
- .tx/config
- invenio_records_ui/templates/invenio_records_ui/export.html
- invenio_records_ui/templates/invenio_records_ui/tombstone.html
- invenio_records_ui/templates/semantic-ui/invenio_records_ui/export.html
- invenio_records_ui/templates/semantic-ui/invenio_records_ui/tombstone.html
- invenio_records_ui/translations/messages.pot
- setup.cfg
> I18n Fix translations backport

- CHANGES.rst
- invenio_records_ui/__init__.py
> release: v1.3.0

- .tx/config
- invenio_records_ui/translations/ar/LC_MESSAGES/messages.po
- invenio_records_ui/translations/bg/LC_MESSAGES/messages.po
- invenio_records_ui/translations/ca/LC_MESSAGES/messages.po
- invenio_records_ui/translations/cs/LC_MESSAGES/messages.po
- invenio_records_ui/translations/da/LC_MESSAGES/messages.po
- invenio_records_ui/translations/de/LC_MESSAGES/messages.po
- invenio_records_ui/translations/el/LC_MESSAGES/messages.po
- invenio_records_ui/translations/et/LC_MESSAGES/messages.po
- invenio_records_ui/translations/fa/LC_MESSAGES/messages.po
- invenio_records_ui/translations/fr/LC_MESSAGES/messages.po
- invenio_records_ui/translations/hr/LC_MESSAGES/messages.po
- invenio_records_ui/translations/hu/LC_MESSAGES/messages.po
- invenio_records_ui/translations/it/LC_MESSAGES/messages.po
- invenio_records_ui/translations/ja/LC_MESSAGES/messages.po
- invenio_records_ui/translations/ka/LC_MESSAGES/messages.po
- invenio_records_ui/translations/ko/LC_MESSAGES/messages.po
- invenio_records_ui/translations/lt/LC_MESSAGES/messages.po
- invenio_records_ui/translations/messages.pot
- invenio_records_ui/translations/no/LC_MESSAGES/messages.po
- invenio_records_ui/translations/pl/LC_MESSAGES/messages.po
- invenio_records_ui/translations/pt/LC_MESSAGES/messages.po
- invenio_records_ui/translations/ro/LC_MESSAGES/messages.po
- invenio_records_ui/translations/ru/LC_MESSAGES/messages.po
- invenio_records_ui/translations/sk/LC_MESSAGES/messages.po
- invenio_records_ui/translations/sv/LC_MESSAGES/messages.po
- invenio_records_ui/translations/tr/LC_MESSAGES/messages.po
- invenio_records_ui/translations/uk/LC_MESSAGES/messages.po
- invenio_records_ui/translations/zh_CN/LC_MESSAGES/messages.po
- invenio_records_ui/translations/zh_TW/LC_MESSAGES/messages.po
> I18n-fix-translations
